node {
	stage('prepare') {
		git branch: 'main', poll: false, url: 'https://github.com/RiteshDevOpsTrainer/restro.git'
	}
	
	stage('build') {
		def mvnHome = tool 'MAVEN'
		withEnv(["MVN_HOME=$mvnHome"]){
			sh '"$MVN_HOME/bin/mvn" clean compile package'
		}
	}
	
	stage('deploy') {
		deploy adapters: [tomcat9(credentialsId: 'da5befdb-1179-4768-9f07-a249ac45ae3a', path: '', url: 'http://13.126.123.137:8080')], contextPath: null, war: '**/*.war'
	}

}
